### ISSUE TITLE
Move to alphabetical property order

### ISSUE THREAD

**Issue by omgaunicorn** [mercari/stylelint-config-mercari#11]
I want to ask if there was any reason to decide on the property order that is currently being used in [this config](https://github.com/mercari/stylelint-config-mercari/blob/master/properties-order.js), so that we can discuss if we can move away from it.

The reason I want to do this is because after working in different teams before, alphabetical is by far the easiest method to adopt between different teams. While I have used other ordering systems like [Mark Dotto's](http://markdotto.com/2011/11/29/css-property-order/) or "outside-in" systems, the reality is that there are no performance benefits at all from using them, and they only add a layer of abstraction to writing CSS that is unneeded.

You can get used to it after a while, but the truth is, whenever new members join our team, it only add one more thing to the pile of knowledge they need to absorb during their first few days, and using alphabetical order is something that you don't need to learn, it can be immediately used and it's the easiest to keep consistent (there are no doubts at all about the order).

This is what Google recommends in it's style guide too: https://google.github.io/styleguide/htmlcssguide.html#Declaration_Order

私は、この設定で現在使用されている不動産秩序を決める理由があるかどうか尋ねたいので、それから離れることができるかどうか議論することができます。

私がこれをやりたいのは、これまでにさまざまなチームで働いた後、アルファベット順が異なるチーム間で採用する最も簡単な方法だからです。私は[Mark Dottoの](http://markdotto.com/2011/11/29/css-property-order/)や「外部」システムのような他の注文システムを使用していましたが、現実にはこれらのシステムを採用することによるパフォーマンス上の利点はなく、不必要なCSSコードを書くための抽象層を追加するだけです。

新しいメンバーが私たちのチームに加わるたびに、最初の数日間は吸収しなければならない知識の山に1つだけ追加し、アルファベット順を使用することはあなたは学ぶ必要はなく、すぐに使用することができ、一貫性を維持するのが最も簡単です（注文について疑問は全くありません）。

これはGoogleのスタイルガイドでも推奨されているものです：https://google.github.io/styleguide/htmlcssguide.html#Declaration_Order

(Sorry for the Google translation!)

**Comment by ggarek** [comment]
Personally, i would not force any particular ordering for css props.

The only reasonable argument for forcing order of css props is for succinct git diff. For this case alphabetic order should be used. Obviously, any other order does not provide this benefit.

Apart from that it has no benefit but adds extra restriction to the project and may affect adoption of this repo.

**Comment by vwxyutarooo** [comment]
I agree what @ggarek say.
I don't want to force like this rule for all of project under Mercari HD. Because for CSS order, benefit isn't enough I think. For example easy to understand, less overhead and less git diff. Easy to understand is personalized. If there aren't rules about order I don't think overhead isn't problem. Then git diff seems benefit to this, I think it's not enough to force it.

This is just my opinion. Personally I used to use [csscomb](https://github.com/csscomb/csscomb.js/blob/dev/config/csscomb.json) order rules however, If there is strong reason to make this rule, I'm okay to use alphabetically order.
